module.exports = {
  ROLES: {
    ADMIN: "ADMIN",
    MANAGER: "MANAGER",
    SURVEYOR: "SURVEYOR",
  },
  SURVEY_STATUS: {
    DRAFT: "DRAFT",
    SUBMITTED: "SUBMITTED",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
  },
  ASSIGNMENT_STATUS: {
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    SUBMITTED: "SUBMITTED",
  },
  SITE_STATUS: {
    PENDING: "PENDING",
    ASSIGNED: "ASSIGNED",
    COMPLETED: "COMPLETED",
  },
};
