export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  SURVEYOR: "SURVEYOR",
};

export const SURVEY_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};
